# Generated by Django 4.2.7 on 2024-01-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Moviename', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('movimg', models.ImageField(null=True, upload_to='')),
                ('year', models.IntegerField(null=True)),
                ('bo', models.CharField(max_length=400)),
                ('director', models.CharField(max_length=400)),
                ('producer', models.CharField(max_length=400)),
                ('cast', models.TextField(null=True)),
                ('rating', models.CharField(max_length=100)),
                ('synopsis', models.TextField(null=True)),
                ('fate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.fate')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Review', models.TextField(null=True)),
                ('Rating', models.CharField(max_length=100)),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('Moviename', models.ManyToManyField(to='one.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Criticreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criticname', models.CharField(max_length=100)),
                ('Review', models.TextField(null=True)),
                ('Experience', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=100)),
                ('Pic', models.ImageField(null=True, upload_to='')),
                ('Moviename', models.ManyToManyField(to='one.movie')),
            ],
        ),
    ]
